# SPDX-License-Identifier: GPL-2.0-only

# Makefile for MHI driver
obj-$(CONFIG_MSM_MHI_DEV) += mhi_mmio.o
obj-$(CONFIG_MSM_MHI_DEV) += mhi.o
obj-$(CONFIG_MSM_MHI_DEV) += mhi_ring.o
obj-$(CONFIG_MSM_MHI_DEV) += mhi_uci.o
obj-$(CONFIG_MSM_MHI_DEV) += mhi_sm.o
obj-$(CONFIG_MSM_MHI_DEV) += mhi_dev_net.o
